routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('players.index');
});
/*Route::get('show', 'PlayersController@ShowPlayers');
Route::get('add-player', 'PlayersController@ShowForm');
Route::post('add-player', 'PlayersController@AddPlayer');
Route::put('player.update', 'PlayersController@EditPlayer');
Route::delete('delete-player/{id}', 'PlayersController@DeletePlayer');*/
Route::resource('players', 'PlayersController');
Route::get('players/{id}/destroy', 'PlayersController@destroy')->name('players.destroy');

app/Player.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    protected $table = "players";
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PlayersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Player;
use Laracasts\Flash\Flash;
class PlayersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $players = Player::all();
        return view('players.index', compact('players'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('players.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $player = new Player();
        $player->name_player = $request->get('name_player');
        $player->lastname_player = $request->get('lastname_player');
        $player->team_player = $request->get('team_player');
        $player->save();
        return redirect()->route('players.show', ['player' => $player->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $player = Player::find($id);
        return  view('players.show', compact('player'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $player = Player::find($id);
        return view('players.edit', compact('player'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $player = Player::find($id);
        $player->name_player = $request->get('name_player');
        $player->lastname_player = $request->get('lastname_player');
        $player->team_player = $request->get('team_player');
        $player->save();
        return  view('players.show', compact('player'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Player::destroy($id);
        return redirect()->route('players.index');
    }
}

resources/views/players/create.blade.php
@extends('template.template')
@section('title')
    Añadir Jugador
@endsection
@section('content')
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
        <div class="panel-body">
        <form action="{{route('players.store')}}" method="POST">
            {{csrf_field()}}
            <label for="name_player">Nombre del Jugador</label>
            <input type="text" class="form-control" name="name_player" placeholder="Ingresa el Nombre">
            <label for="lastname">Apellido del Jugador</label>
            <input type="text" class="form-control" name="lastname_player" placeholder="Ingresa el Apellido">
            <label for="team">Equipo del Jugador</label>
            <input type="text" class="form-control" name="team_player" placeholder="Ingresa el Equipo">
            <hr>
            <button type="submit" class="btn btn-primary">Agregar Jugador</button>
            <hr>
        </form>
        </div>
    </div>
</div>

@endsection

resources/views/players/edit.blade.php
@extends('template.template')
@section('title')
    Modificar Jugador
@endsection
@section('content')
{!! Form::open(['route' => ['players.update', $player], 'method' =>'PUT']) !!}
    <div class="container">
    <h1>Ingresa los nuevos datos de: {{$player->name_player}} </h1>
        <div class="form-group">
            {!! Form::label('name', 'Nombre') !!}
            {!! Form::text('name_player', $player->name_player, ['class' => 'form-control', 'placeholder' => 'Nombre del Jugador']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Apellido') !!}
            {!! Form::text('lastname_player', $player->lastname_player, ['class' => 'form-control', 'placeholder' => 'Apellido del Jugador']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Equipo') !!}
            {!! Form::text('team_player', $player->team_player, ['class' => 'form-control', 'placeholder' => 'Equipo del Jugador']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Guardar Modificaciones', ['class' => 'btn btn-primary']) !!}
        </div>
    </div>
{!! Form::close() !!}
@endsection

resources/views/players/index.blade.php
@extends('template.template')
@section('title')
    Lista de Jugadores
@endsection
@section('content')
    <div class="jumbotron jumbotron-fluid bg-dark">
        <div class="container">
            <h1 class="display-4 text-white">Jugadores Registrados</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Equipo</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                @if($players->isEmpty())
                    <th scope="row">No hay registros que mostrar</th>
                    @else 
                    @foreach($players as $player)
                        <tr>
                            <th scope="row">{{$player->id}}</th>
                            <td>{{$player->name_player}}</td>
                            <td>{{$player->lastname_player}}</td>
                            <td>{{$player->team_player}}</td>
                            <td>
                                <a href="{{route('players.edit', $player->id)}}" class="btn btn-primary">Modificar</a>
                                <a 
                                href="{{route('players.destroy', $player->id)}}" 
                                onclick="return confirm('¿Deseas elimminar el jugador seleccionado?')"
                                class="btn btn-danger">Eliminar
                                </a>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/players/show.blade.php
@extends('template.template')
@section('title')
    Registro Exitoso
@endsection
@section('content')
<div class="jumbotron jumbotron-fluid bg-dark">
        <div class="container">
            <h1 class="display-4 text-white">Registro Exitoso del jugador</h1>
            <h1 class="text-white">{{$player->name_player}} {{$player->lastname_player}}</h1>
        </div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="container">
                        <div class="row">
                            <h1 class="text-white">Nombre del Equipo : </h1>
                            <h1 class="text-white">{{$player->team_player}}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/template/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{route('players.index')}}">CRUD Laravel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{route('players.index')}}">Inicio <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('players.create')}}">Registrar Jugador</a>
        </li>
        </ul>
    </div>
    </nav>
    @yield('content')
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>